### ISSUE TITLE
URLs to Service Hub files give a 404

### ISSUE THREAD

**Issue by beerendlauwers** [atom-haskell/haskell-ghc-mod#16] opened 2015-05-29 08:42 UTC
Links to these files give a 404: 

ide-backend.coffee
completion-backend.coffee

**Comment by lierdakil** [comment] 2015-05-29 15:10
Duplicate of #15, fixed in master. Will push a new version to atom.io in a bit.

**Closed by lierdakil** 2015-05-29 15:10 UTC
Labels: duplicate
