### ISSUE TITLE
Use .hlint.yaml

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/haskell-ghc-mod#209] opened 2017-04-07 09:59 UTC
Currently it seems that the file is ignored. When I run `hlint` from the command line it takes the configuration into account, but linting from inside of the editor ignores it.

**Comment by lierdakil** [comment] 2017-04-10 22:42
This is likely caused by the fact that ghc-mod runs hlint programmatically (as opposed to calling the binary). There are a couple known bugs, that should theoretically be fixed by https://github.com/DanielG/ghc-mod/pull/829. But that patch is unreleased as of now. Honestly, the release schedule of ghc-mod has been kinda horrible lately. At this point I'm kinda tempted to eschew ghc-mod entirely wrt linting, and instead use hlint directly, but that's quite a bit of work honestly, and makes setup that much more complicated, so yeah...

**Comment by matonix** [comment] 2017-09-11 14:54
FYI: in my environment (ghc-mod version 5.8.0.0 compiled by GHC 8.0.2), the following option worked.

```
- ignore: {name: Eta reduce}
```

**Comment by lierdakil** [comment] 2017-09-11 15:37
Well, that's because referenced PR finally found its way into ghc-mod 5.8. Thanks for the heads-up.

**Closed by lierdakil** 2017-09-11 15:37 UTC
