### ISSUE TITLE
Looks like ghc-modi craHSed

### ISSUE THREAD

**Issue by cblp** [atom-haskell/haskell-ghc-mod#67] opened 2015-11-20 12:32 UTC
```
Looks like ghc-modi crahsed
Haskell-ghc-mod: ghc-modi crashed on info with message  in /tmp/hakyll-4.7.4.0
                                                       ^?

Looks like ghc-modi crahsed
Error: This socket is closed.
```
Atom 1.2.2
haskell-ghc-mod 1.1.5
ghc-mod 5.4.0.0

**Comment by lierdakil** [comment] 2015-11-22 16:38
Whelp, apparently it just crashed with no message.

**Comment by WillSewell** [comment] 2015-11-22 22:05
I also get this error frequently.

**Comment by rvion** [comment] 2015-11-23 08:57
me too

**Comment by rvion** [comment] 2015-11-23 10:45
it only crashes when linting is enabled

**Comment by rvion** [comment] 2015-11-23 11:14
I have the impression (to be confirmed) that installing latest ghc-mod and hlint with `stack --resolver=nightly install hlint ghc-mod` fixes the problem

**Comment by lierdakil** [comment] 2015-11-23 15:57
Check console after crash. Chances are, there is an error message there with some more information.

**Comment by apriori** [comment] 2015-11-28 19:38
@rvion 
That doesn't seem to fix it for me. So far this bug is kind of getting annoying, because it literally results in a popup spam.

**Comment by lierdakil** [comment] 2015-12-01 04:54
@rvion, if it crashes on lint, then error message should read "ghc-modi crashed on ***lint*** ...", not "***info***" as in OP.

I really don't have enough information to figure out what is going wrong.

**Comment by leon1995** [comment] 2015-12-03 11:00
I get the same error massage. It says ghc-modi crashed on info with massage /the path from my data witch I have open.

**Comment by lierdakil** [comment] 2015-12-03 18:25
Found a race condition that could contribute to this issue. haskell-ghc-mod 1.1.7 should fix it, but I'm not sure it will solve this issue completely. Feedback is appreciated.

**Comment by WiWa** [comment] 2015-12-08 01:15
I'm getting this error on 1.2.0.

**Comment by lierdakil** [comment] 2015-12-08 18:35
@WiWa, there may be a legitimate reason why ghc-modi would crash. If you can reproduce this issue consistently, and are convinced that your configuration is correct, I would ask you to share the method.

**Comment by WiWa** [comment] 2015-12-09 08:29
How would I make sure my configuration is correct?

**Comment by lierdakil** [comment] 2015-12-16 14:52
@WiWa, sorry about late reply, I've been very short on time last week.

Make sure that `ghc-pkg check` doesn't complain about broken packages. Make sure your cabal project can be configured (`cabal configure` it from terminal and see the output).

Also, while at it, check if ghc-mod works for your project at all (`ghc-mod check main-file.hs` and `ghc-mod lint main-file.hs`, where `main-file.hs` is path to your project's main file -- executable or library, doesn't really matter).

**Comment by lierdakil** [comment] 2015-12-16 14:54
P.S. If your project uses stack, use `stack build --only-configure` instead of `cabal configure`

**Comment by WiWa** [comment] 2015-12-16 16:38
`ghc-mod check` and `ghc-mod lint` both work fine. I can actually get this error editing a simple .hs file without being in a directory with a .cabal file. 

`ghc-pkg check` seems to give a lot of `warning: haddock-interfaces` and `warning: haddock-html:` messages for my cabal libraries, that some file its looking for doesn't exist.

**Comment by lierdakil** [comment] 2015-12-16 16:50
Haddock warnings are normal. You only should look for something like this near the end of `ghc-pkg check` output:

```
The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
package-version
package-version
...
```

One last thing to check if you're on OSX. If you run Atom from terminal, does this error still happen?

**Comment by WiWa** [comment] 2015-12-16 16:53
No such message appears. Will report back on opening from terminal.

**Comment by WiWa** [comment] 2015-12-16 22:14
Haven't seen the error yet from terminal. Why would it go away? I'm using Ubuntu 14. WIll try on Windows tonight.

**Comment by lierdakil** [comment] 2015-12-17 19:10
@WiWa, running from terminal only makes a difference on OSX (i.e. Mac), due to the fact that environment can change between terminal and launcher there.

Okay, so let me get this straight: ghc-modi apparently crashes every now and again for no good reason. You have no idea on how to *make* it do that on purpose. Well. Only thing I can suggest at this point is to enable 'Debug' option in haskell-ghc-mod settings, and post dev. console output once it crashes again. Bear in mind, it's quite a lot of output, so use gist or something when (if) posting. You can open dev. console with View → Developer → Toggle Developer Tools

**Comment by lierdakil** [comment] 2016-01-02 02:57
Due to updated error reporting capabilities, I'm closing this. If anyone runs into a similar issue, use Atom's built-in issue reporting feature ('Create new issue' button in error message)

**Closed by lierdakil** 2016-01-02 02:57 UTC
